[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[[redirects]]
  from = "https://www.jrglassworks.com/*"
  to = "https://jrglassworks.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/api/*"
  to = "https://api.jrglassworks.com/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.google-analytics.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https:; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://api.jrglassworks.com;"

[context.production.environment]
  NODE_ENV = "production"
  VITE_API_URL = "https://api.jrglassworks.com"

[context.deploy-preview.environment]
  NODE_ENV = "staging"
  VITE_API_URL = "https://staging-api.jrglassworks.com"

[context.branch-deploy.environment]
  NODE_ENV = "staging"
  VITE_API_URL = "https://staging-api.jrglassworks.com"
